version: "3.9"  # optional since v1.27.0
# Services
services:
  # MongoDB
  mongodb:
    ports:
      - "27017:27017"
    image: mongo:latest
    restart: always
    environment:
      # Change this to your credentials
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_datadir:/data/db
  # MariaDB
  mariadb:
    ports:
      - "3306:3306"
    image: mariadb:latest
    restart: always
    environment:
      # Change this to your credentials
      MARIADB_ROOT_PASSWORD: super-secret-passwd
      MARIADB_DATABASE: siru
    volumes:
      - mariadb_datadir:/var/lib/mysql
  # SiruBOT Client
  sirubot:
    build: .
    command: node ./build -d -s -c settings.yaml
    volumes:
      - ./build:/opt/sirubot/build
      - ./settings.yaml:/opt/sirubot/settings.yaml
    depends_on:
      - mariadb
      - mongodb
    links:
      - mongodb
      - mariadb

# Volumes
volumes:
  mongodb_datadir:
  mariadb_datadir: