name: Docker Build

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use nelonoel/branch-name
        uses: nelonoel/branch-name@v1.0.1
      -
        name: Build the docker image
        
        run: "echo Branch: ${BRANCH_NAME} Hash: ${{ github.sha }} && docker build -t sannoob/sirubot:${BRANCH_NAME}-${{ github.sha }} -f ./Dockerfile ."