name: Docker Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build the docker image
        run: echo Branch ${{ github.head_ref }} hash ${{ github.sha }} && docker build -t sannoob/sirubot:${{ github.head_ref }}-${{ github.sha }} -f ./Dockerfile .