# Eslint 를 실행합니다

name: Run eslint tests

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --production=false
    
    - name: Test with eslint
      run: yarn run lint